DROP TABLE CALENDAR
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CAL;

CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	RDATE VARCHAR2(12) NOT NULL,
	WDATE DATE NOT NULL

);

CREATE SEQUENCE SEQ_CAL
START WITH 1
INCREMENT BY 1;

ALTER TABLE CALENDAR
ADD CONSTRAINT FK_CAL_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM CALENDAR;

SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM (										-- 모든 날짜 (년, 월, 일) 가져옴
		SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(RDATE, 1, 8)ORDER BY RDATE ASC ) AS RNUM,
				SEQ, ID, TITLE, CONTENT, RDATE, WDATE
		FROM CALENDAR
								-- 월 날짜 가져오기 
		WHERE ID=? AND SUBSTR(RADATE, 1, 6)=?    
)

WHERE RNUM BETWEEN 1 AND 5;

SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM (										
		SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(RDATE, 1, 8)ORDER BY RDATE ASC ) AS RNUM,
				SEQ, ID, TITLE, CONTENT, RDATE, WDATE
		FROM CALENDAR
								
		WHERE ID='aaa' AND SUBSTR(RDATE, 1, 6)='202008'    
)

WHERE RNUM BETWEEN 1 AND 5;

SELECT SEQ, TITLE , WDATE
FROM CALENDAR
WHERE ID= 'aaa' AND RDATE LIKE '20200806%'
ORDER BY RDATE ASC;


SELECT SEQ, TITLE , WDATE
FROM CALENDAR
WHERE ID= 'aaa' AND WDATE BETWEEN TO_DATE('20200806','YYYYMMDD') AND TO_DATE('20200806 23:59:59', 'YYYYMMDD HH24:MI:SS')  
ORDER BY RDATE ASC;